### ISSUE TITLE
Refactor display of cafeteria menus in card and fragment

### ISSUE THREAD

**Issue by thellmund** [TUM-Dev/Campus-Android#1070]
We currently display cafeteria menus in the card view and in the fragment by manually sticking views together in a `LinearLayout`. To simplify our code, we should switch to another component (potentially a `RecyclerView`?).

**Comment by kordianbruck** [comment]
@thellmund done?

**Comment by thellmund** [comment]
Nope. I’ve tweaked the style, but did not changed the used components yet.

**Comment by thellmund** [comment]
Done in #1246.
