### ISSUE TITLE
MainActivity.onAlwaysHideCard() crashes with index -1

### ISSUE THREAD

**Issue by pfent** [TUM-Dev/Campus-Android#1153]
>ArrayIndexOutOfBoundsException
>length=10; index=-1
>CardAdapter.remove (CardAdapter.java:104)
>MainActivity.onAlwaysHideCard (MainActivity.java:199)

probably do a sanity range check here

**Comment by thellmund** [comment]
I’ve pushed a quick fix in #1155, but will investigate the actual cause.

**Comment by thellmund** [comment]
Prevented with #1307.
