### ISSUE TITLE
Dark mode 

### ISSUE THREAD

**Issue by kordianbruck** [TUM-Dev/Campus-Android#1157]
So we now have more white. First suggestion just came in for a dark mode.

https://app.tum.de/Feedback/af98c6af-24b5-4bb8-91b4-69fce8ab6eda

@thellmund :dagger:

**Comment by thellmund** [comment]
Can be done via [DayNight](https://medium.com/androiddevelopers/appcompat-v23-2-daynight-d10f90c83e94) theme. Assigning a low priority to this, because we should first spend some time polishing after the v2.0 update.

**Comment by kordianbruck** [comment]
This was attempted in https://github.com/TUM-Dev/Campus-Android/pull/1273 but never finished. Just for refrence.

**Comment by SiKreuz** [comment]
The only thing to do is, create `values-night/colors.xml` in the resource directory and add an option in the configurations. I can do that. Just need some time to find all the relevant color variables.

**Comment by kordianbruck** [comment]
The issue with the colors is that the styling is a bit f'd up. I've basically just recently tried to debug a lot of the cases where we had white on white buttons and this is just incredibly difficult. A lot of layouts set custom colors instead of using proper styles / colors. So it might end up being a case of: "you have to do a lot of additional work to get this working"

**Comment by SiKreuz** [comment]
Yeah. I'm already cleaning up stuff to get a better overview. But cleaning up in general would be nice for the app. So I'm more focusing on the dark mode now, but fixing what I find.

**Comment by kordianbruck** [comment]
nice!
