### ISSUE TITLE
SecurityException: Too many alarms registered

### ISSUE THREAD

**Issue by pfent** [TUM-Dev/Campus-Android#1162]
@thellmund already tried to fix this issue with f5037b67eae1477da37c5656c523f060798a6a19, but that apparently didn't fix the issue.

I guess we need to keep track of the "active" notifications by manually counting how many are active. I.e. increment in `scheduleAlarm()` and decrement in `NotificationAlarmReceiver.onReceive()`

**Comment by thellmund** [comment]
That does not take into account the importance of a notification. What if we end up blocking a tuition fees notification because of a (rather unimportant) transport notification? 

Instead, we should reconsider further how many notifications we schedule in the first place (e.g. do we really need to schedule alarms for transport notifications in 5 days?). What do you think, @kordianbruck @jacqueline8711 @pfent?

**Comment by kordianbruck** [comment]
Firebase: https://console.firebase.google.com/project/tca-backend-0001/crashlytics/app/android:de.tum.in.tumcampus/issues/5bc737f0f8b88c2963242e81

Yes, exactly my though. Like the next 10-15 should really be enough.

**Comment by pfent** [comment]
>Like the next 10-15 should really be enough

Very scientific answer :man_scientist: :rofl: 
I think we have the BackgroundService running like every 3 hours. Scheduling notifications for *at most* the next 6 hours should really be sufficient.

Nevertheless, we can only guesstimate how many parallel notifications there are, so scheduling notifications really only is best effort. IMHO we should still track the active notifications and limit it to 100.

Suppose we have a user signing up for *all the lectures* and we schedule 500+ next lecture notifications -> :bomb:

**Comment by kordianbruck** [comment]
So either next 6 hours or maximum of 10 lectures. All agree?

**Comment by kordianbruck** [comment]
Reappears: https://console.firebase.google.com/project/tca-backend-0001/crashlytics/app/android:de.tum.in.tumcampus/issues/5bd718c8f8b88c2963afa395?time=last-seven-days&sessionId=5BD718B7014600012A06CE8773B4F598_DNE_0_v2

**Comment by pfent** [comment]
@kordianbruck that might be a false positive.
If the last version already scheduled 500 alarms, we can't possibly track how many more to schedule.

Give it some time, if we still get fresh crashes in a couple of days, I'll investigate further

**Comment by kordianbruck** [comment]
Small Update: the latest release does seem to improve the overall situation and prevent some crashes. Still on 13.11.2018 we had 25 crashes happen related to this exception. I'll monitor it further and we might revisit this after the 3.0 is released.
