### ISSUE TITLE
Calendar: too much spacing

### ISSUE THREAD

**Issue by kordianbruck** [TUM-Dev/Campus-Android#1172]
We are getting complaints, that the calendar is not the best, as with many events, nothing gets displayed. Could we maybe reduce the spacing inside? Reduce font size?
The Dayview seems okaish. The Week view is really bad. Other ideas?

![screenshot_2018-10-26-10-41-48](https://user-images.githubusercontent.com/298860/47555760-ec2ce400-d90c-11e8-8dce-7eb4ced4f663.jpg)
![screenshot_2018-10-26-10-40-50](https://user-images.githubusercontent.com/298860/47555761-ecc57a80-d90c-11e8-8226-1c1d93191d47.jpg)

**Comment by pfent** [comment]
I just think you're not supposed to have 4 lectures at the same time :man_shrugging: 

I think smaller font sizes won't really improve on this, since the text is already kinda hard to read. The only thing a can come up with, would be some kind of abbreviation system, but that's really hard for the general case, especially for german titles...
Maybe run something to split up compound words (like [this](https://github.com/danielnaber/jwordsplitter)) then build an abbreviation of the first letters of those components?

Otherwise we can also provide a horizontal version of the week view, so people could rotate their phone...

**Comment by kordianbruck** [comment]
It works in horizontal viewmode, no problemo. On the very left there are no letters displayed at all. I know that 4 events is not normal, but it was working better with our previous calendar version. (At least the user says so)

So lets sum up, what things we can try: 
(@jacqueline8711 is an expert in calendars & finding those extra pixels :rofl: )

- [ ] No bold text
- [ ] Less spacing between events
- [ ] Smaller text size
- [ ] third display mode: next 3 days
- [ ] Text in vertical mode, so maybe its more readable? (Rotate 90°)
- [ ] ???

Please post some things that you try from that list

**Comment by thellmund** [comment]
I think that’s a problem in the framework. Since we're using my fork since a few weeks, I can take a look at horizontal spacing. 

Also, if you have a such a packed schedule, week view is just not for you.

**Comment by kordianbruck** [comment]
> Kommentar zu neuem Design: Die Lücke zwischen Aktivitäten im Kalender ist unpraktisch erhöht. 

Its not something users are imaging. Previously the spacing between the items was less, as I've read on multiple accounts now. Saying that the users schedule is too packed for the view is easy to say. I have a similarly packed schedule in Google Calendar and it is still usable.

**Comment by jacqueline8711** [comment]
Just reducing some paddings and margins makes it more readable (see example)
And if we allow the user to hide lectures (--> #408) it should become readable even if you sign up to a lot of  different lectures/courses. 

![screenshot_1540984921](https://user-images.githubusercontent.com/16260112/47785013-ba01f480-dd07-11e8-878e-34cfc236960a.png)

**Comment by thellmund** [comment]
@jacqueline8711 That might be the easiest fix for now. But it would probably be a good idea to only apply this in week view, as the day view should offer enough space.

**Comment by kordianbruck** [comment]
@thellmund I disagree, shouldn't we opt for a consistent view? Does the increased user spacing add any user value? Does it improve readability? Kinda relevant questions that we want to evaluate right? 

@jacqueline8711 can you maybe upload two screenshots as well for the day view, so we have a direct comparison?

**Comment by thellmund** [comment]
@kordianbruck You answered your own question: Padding and whitespace improves readability. I think it makes sense to opt for more padding where we can afford it (day view) and less padding where space is precious (week view).

**Comment by jacqueline8711** [comment]
@thellmund I don't see how padding and whitespace would improve readability here. I would much rather see as much of the title as possible as long as the events aren't glued together. 
I'd say the first image in this issue is a good example of why we should also decrease the spacings in the day view.

**Comment by pfent** [comment]
Another drawback of larger paddings are smaller touch targets to actually click on the event...

@thellmund I think you find yourself outvoted 😏

**Comment by thellmund** [comment]
@pfent Padding is within an element, not around an element. Increasing padding won’t reduce the touch target size.

**Comment by jacqueline8711** [comment]
Example day view with conflicts
![screenshot_1540991641](https://user-images.githubusercontent.com/16260112/47790429-71523780-dd17-11e8-8a19-87224f62bfe9.png)

**Comment by pfent** [comment]
@thellmund then should I file a bug report with your library?

I can't touch the calendar items in the space between items. So what we have is *technically* no padding :wink:

**Comment by jacqueline8711** [comment]
Can we close this issue? I think it looks fine now.

**Comment by kordianbruck** [comment]
@jacqueline8711 I'm still wondering, if we should reduce the font size for the events. If I see the Google Calendar correctly, they use a smaller font for the event text and the title is also not as bold as we currently have it set. Does it make sense to play some more? 

I can gather some feedback from users whenever we release the next major version 3.0.

**Comment by jacqueline8711** [comment]
@kordianbruck Yes, I guess we can make the fond a little smaller. 
The bold text is nice for finding the location easily. Maybe we can make the title not bold and add a line break before the location instead? Or do you mean that we should make it a medium bold font?

**Comment by kordianbruck** [comment]
@jacqueline8711 yea, less bold. Seems to me this is currently something 500+ in weight, but 300-400 should be enough to distinguish it from the location.

**Comment by thellmund** [comment]
The font weight is dictated by the library. I will look into allowing customization of it. Same goes for having the event location below the title, not behind it.

**Comment by thellmund** [comment]
Can this be closed? @jacqueline8711 made some adjustments and I’ve just opened #1239.
