### ISSUE TITLE
Opening Times Cafeteria wrong

### ISSUE THREAD

**Issue by kordianbruck** [TUM-Dev/Campus-Android#1225]
Similar to #1211 

> Campus App angezeigten Öffnungszeiten für die Mensa stimmen manchmal nicht (z.B. heute hatte die Mensa bis 16 Uhr auf, aber angezeigt wurde, dass die Mensa ab 14 Uhr geschlossen hatte).

**Comment by thellmund** [comment]
It seems that we’re no longer receiving any opening hours for the cafeterias. Any ideas what could be the cause, @jacqueline8711 @kordianbruck?

**Comment by jacqueline8711** [comment]
Yes, the new IDs don't match the old ones so the reference is broken. I'll fix it on Thursday I guess
