### ISSUE TITLE
Allow Sale of multiple tickets

### ISSUE THREAD

**Issue by kordianbruck** [TUM-Dev/Campus-Android#1227]
We want to enable users to not only buy one ticket, but let them buy a variable amount up to X. (X is served with the ticket type, inside the ticket payment, being the max tickets of this type that the user is allowed to buy)

**Comment by jacqueline8711** [comment]
How will the ticket check work if one user has multiple tickets? Do we already have any plans for that?

**Comment by kordianbruck** [comment]
@jacqueline8711 the checkin dialog should show the number of tickets for that ticket, that is being redeemed. For now a ticket should still only be redeemed once.
