### ISSUE TITLE
Add a notification preview / test screen [1 day]

### ISSUE THREAD

**Issue by pfent** [TUM-Dev/Campus-Android#1235]
Follow up from previous issues; #879, #1162, #1165

Even though we really tried to fix this issue, we're still getting occasional crashes in `NotificationScheduler`.
Also the current way of throttling Notifications isn't exactly nice or precise :disappointed:.

As a first step to tackle this, I'd like to introduce a notification preview screen (probably buried somewhere in the settings), which displays all scheduled notifications.

Added benefit:
* Users see all notifications we have currently scheduled for them
* We can give users more control over the notifications, maybe even allow them to adjust the frequency we schedule some notifications
* Add a possibility to debug notifications and enhance the intelligence part of notification scheduling

**Comment by kordianbruck** [comment]
Good idea, this would also allow for devs an easier access to check if their coded notification actually works...

**Comment by thellmund** [comment]
Great idea to make debugging easier. I don’t think it will be of interest to end users, but if we bury it “somewhere in the settings”, that should be fine.

**Comment by kunzef** [comment]
Hey, just wanted to know if the preview is still needed? If so I would like to try to implement it.
