### ISSUE TITLE
Add opening hours throughout the app

### ISSUE THREAD

**Issue by jacqueline8711** [TUM-Dev/Campus-Android#1264]
- [x] add SSZ opening hours for financial aid + keep link to Student Financial aid (contact is ssz) in tuition fees screen
- [x] show opening hours for all cafeterias

Related: #491, #1225

**Comment by i-walker** [comment]
Here are some Screenshots. On the updated Database integrated into the App.

My thoughts on the API:
We should specify where exactly each column is located.
I did this in my prototype with a primitive StringBuilder, so I would not break the legacy code. 
I think we should rewrite these components. 
Affected classes are:
- Location.kt 
//this should take a Json as an Input and populate the data class
- CafeteriaLocationImportAction.kt 
- OpeningHoursDetailFragment.java
- OpeningHoursListActivity.java
- OpeningHoursDetailActivity.java
//they load and display the Information of the Database. I think this will be deleted anyway

<img width="336" alt="Screenshot 2019-03-11 at 17 37 03" src="https://user-images.githubusercontent.com/46971368/54140737-9755ba00-4424-11e9-8655-21f1f06dbbd3.png">
<img width="325" alt="Screenshot 2019-03-11 at 17 37 15" src="https://user-images.githubusercontent.com/46971368/54140742-99b81400-4424-11e9-9cb8-8043d429883c.png">
<img width="309" alt="Screenshot 2019-03-11 at 17 36 28" src="https://user-images.githubusercontent.com/46971368/54140751-9fadf500-4424-11e9-8d3c-3038b0b02b93.png">
<img width="320" alt="Screenshot 2019-03-11 at 17 36 17" src="https://user-images.githubusercontent.com/46971368/54140758-a50b3f80-4424-11e9-81b5-e1e5ee465b7c.png">
