### ISSUE TITLE
Please also include v1  (JAR) signatures

### ISSUE THREAD

**Issue by IzzySoft** [TUM-Dev/Campus-Android#1266]
The latest APK (3.1-Beta) lacks v1 signatures:

```
$ apksigner verify de.tum.in.tumcampus_3.1.apk
DOES NOT VERIFY
ERROR: No JAR signatures
```

Could you please keep them included (Android Studio meanwhile has them disabled by default)? Else I cannot serve the latest version [here](https://apt.izzysoft.de/fdroid/index/apk/de.tum.in.tumcampus) (maybe not that important for the Betas, but for the next release it would be nice; I've currently told my updater to skip pre-releases for your app).

Thanks in advance!

**Comment by jacqueline8711** [comment]
My apologies, this was the first apk I have signed and I was not aware the v1 signature was still needed. I have updated the 3.1-Beta apk and will include both signatures in the future

**Comment by IzzySoft** [comment]
Thanks, @jacqueline8711! To explain why it's needed (apart from `apksigner` complaining): v2 is supported from Android 7 upwards. Android 6 and below would still need v1. Your app targets Android 5 – but would not install on either 5 or 6 without v1 signatures.

So thanks for replacing the APK! Do you want me to pick up pre-releases for my repo as well – or shall I better stick to the "finals"? Either is fine for me – it's rather a question of what audience you have in mind for the pre-releases :wink:
