### ISSUE TITLE
Don't show new grades notification again after dismissing

### ISSUE THREAD

**Issue by jacqueline8711** [TUM-Dev/Campus-Android#1287]
## Steps to Reproduce

1. Receive a new grade (on TUMonline)
2. Dismiss notification instead of clicking on it
3. Notification will pop up every hour or so

## Expected Result
It shouldn't show again after dismissing it (user probably has already checked the grade in TUMonline if they are dismissing it)

## Actual Result
The notification only stops showing after opening the grades view

### Environment
* Phone: Pixel XL
* OS version: 9
* TUM Campus App version: 3.2-dev
* Language: English

**Comment by thellmund** [comment]
I worked on this some time ago, but didn’t make a pull request for it. Have now done so at #1295. Feel free to make changes if you see fit 😊
