### ISSUE TITLE
Reoccurring calendar entries

### ISSUE THREAD

**Issue by kordianbruck** [TUM-Dev/Campus-Android#1297]
User requested to be able to create calendar entries, instead of single date entries. (Similar to how its possible in TUMonline)

I think we will need to adapt the API in TUMonline for this unfortunately.

**Comment by thellmund** [comment]
Should this really be a functionality of the Campus App or should the user instead use the Calendar app on their phone?

**Comment by kordianbruck** [comment]
A lot of people like to use the TUMonline calendar that has all their lectures included. The also sync this to various devices. It could be added to the app but also people can export the calendar on android. (that also is used a lot)

So I think it might be reasonable to add it, as it should not be too much work.
