### ISSUE TITLE
Maximum zoom for calendar

### ISSUE THREAD

**Issue by kordianbruck** [TUM-Dev/Campus-Android#1299]
![image](https://user-images.githubusercontent.com/298860/56661709-2a565680-6657-11e9-95b1-7adce3e908da.png)

currently the calendar allows to zoom out indefinitely. A better UX would limit the zoom out level.

**Comment by thellmund** [comment]
The app still uses an old version of [WeekView](https://github.com/thellmund/Android-Week-View). I’ll update to the new version, which should address the issue (at least I can’t reproduce a similar behavior in the sample app).
