### ISSUE TITLE
Add opening hours data in English

### ISSUE THREAD

**Issue by jacqueline8711** [TUM-Dev/Campus-Android#1301]
- [ ] translate the opening hours data (mostly titles and some of the info notes) and add it as a new table to the server db
- [ ] add a new endpoint for the english data
- [ ] download data from one or the other endpoint from the app depending on the app language setting (use string from strings.xml to determine language)

**Comment by kordianbruck** [comment]
I'd just have a parameter with the same endpoint. It really makes no sense to have a separate table, instead expand the current table and add a language column

**Comment by jacqueline8711** [comment]
We can use a parameter, doesn't make a difference to me.
But I thought a separate table might be easier since we are getting the opening hours out of that data by using the id, so the German and English version should have the same id so we don't have to make changes, or at least the id that is sent to the app (an extra column with that id is possible too)
Although on that note I just saw that the cafeteria opening hours are broken since the new opening hours have new ids and not the ones from the cvs file --> we should probably change the location ids, since changing the ids for the cafeteria would break old versions with the cvs files.

**Comment by kordianbruck** [comment]
You should not account for having the same DB id at any time. Those can change without previous knowledge. If you want, we can add identifiers that will be static. I'd rather just have a row each in the db with a language field and maybe output both versions in a single row. (So join them together via an Identifier or something)
