### ISSUE TITLE
MVV-Card Issue

### ISSUE THREAD

**Issue by BastidB** [TUM-Dev/Campus-Android#1349]
It's not possible to change the preferred stop in the settings of the MVV-card.
I want to change the preferred stop from "Theresienstraße" to "Pinakotheken".
While the change is visible in the settings, the card does still give me information about the "Theresienstraße".

### Environment
* Phone: Samsung Galaxy S10
* OS version: 9
* TUM Campus App version: v3.4
* Language: German

**Comment by Liqs-v2** [comment]
I'd be interested in looking into this, as far as my research is concerned this bug is still in the current version of the app.

**Comment by Liqs-v2** [comment]
I am working on this in #1409

**Comment by Liqs-v2** [comment]
Fixed in #1409
