### ISSUE TITLE
Fastlane changelogs

### ISSUE THREAD

**Issue by IzzySoft** [TUM-Dev/Campus-Android#1351]
Somehow, Fastlane changelogs have not been added for new releases since versionCode 522 (about 2 years ago). Could that be fixed? Maybe at least starting with the latest release, and continued from there onwards? Thanks!

**Comment by IzzySoft** [comment]
Thanks, that filled a gap. But the latest release is `versionCode:567`, while the latest changelog now is `544.txt`. Will `567.txt` (and future ones) be added as well – maybe at the time of tagging their release so they are picked up along? The most recent ones are those which are most important.

**Comment by CommanderStorm** [comment]
Actually I am unclear where the versions between 544 and 567 are.. I went trough our releases cronologically and added every release.
The numbering on the releases seems off. I have not investigated them. Probably some were bugfix releases without an actual release noted in github..
In the future I think we can keep that up, but I dont know where these numbers went missing/spawned.
My current plan is to do a large version jump for these missing changelogs next version (i.e. use `568` instead of `545`)

**Comment by CommanderStorm** [comment]
Is this sufficient?

**Comment by IzzySoft** [comment]
> Actually I am unclear where the versions between 544 and 567 are.

My updater picks APKs attached to your releases. You've stopped attaching them around 2019 it seems (the last one [listed in my repo](https://apt.izzysoft.de/fdroid/index/apk/de.tum.in.tumcampus) identifies as `versionName: "3.4"` with `versionCode: 567`, dated 2019-04-22. [`build.gradle` at that tag](https://github.com/TUM-Dev/Campus-Android/blob/3.4/app/build.gradle#L41) says 3.5-dev and 368, so the corresponding APK most likel was built before the tag was created. Same seems to go for your latest release: tagged as 3.18, but having 3.19-dev and 585. So I indeed wonder where you checked :wink: 

> In the future I think we can keep that up, but I dont know where these numbers went missing/spawned.

That'd be great – especially if you'd attach APKs again :smiley:

> My current plan is to do a large version jump for these missing changelogs next version (i.e. use 568 instead of 545)

Ugh… which direction does that jump go if you want to use 568 while your latest code already passed 585? Are we both referring to the same thing?

**Comment by CommanderStorm** [comment]
> Ugh… which direction does that jump go if you want to use 568 while your latest code already passed 585? Are we both referring to the same thing?

Jea.. I meant 586 not 568 xD

**Comment by IzzySoft** [comment]
That of course fits then. And though I think you know, just to make sure we mean the same here as well: naming of the changelog files is `<versionCode>.txt` – so that one would be `586.txt` then :smile:
