### ISSUE TITLE
Coloring of uncommon grades

### ISSUE THREAD

**Issue by logolive** [TUM-Dev/Campus-Android#1357]
## Steps to Reproduce

1. Get (Simulate) a grade of (say) 1.5
2. In the app, navigate to "My Grades"
3. Look at the grade's background color

## Expected Result
As 1.5 lies between 1.4 and 1.7, the color should be somewhat greenish

## Actual Result
It shows up as grey.

## Problem
Grades outside the X.{0,3,4,7} scheme rarely appear.
Still they are possible whenever several grades are combined.
See e.g. the interdisciplinary project in M.Sc. Informatics,
which consists of two seperately graded parts worth 5 and 11 ECTS.

Based on the Color wheel at the top (which doesn't even show the grade even in it's grey color)
I assume that colors were assigned to individual grades rather than defined for the entire spectrum 1.0-5.0 .

## Suggested Enhancement :sparkles:
If this assumption holds, replace the color association by some continuous function.
E.g. use interpolation or something simple like that.

### Environment
* Phone: Blackview BV 8000 Pro
* OS version: Android 7.0
* TUM Campus App version: 3.5 (Version Code 571)
* Language: English (US)

**Comment by kordianbruck** [comment]
Thansk to @joschahenningsen for fixing this!
