### ISSUE TITLE
Implement In-App Review API

### ISSUE THREAD

**Issue by kordianbruck** [TUM-Dev/Campus-Android#1363]
https://developer.android.com/guide/playcore/in-app-review

would be nice to get some more good ratings.

**Comment by Liqs-v2** [comment]
Is someone working on this?

**Comment by Liqs-v2** [comment]
If not I'd pick this up too.

**Comment by Liqs-v2** [comment]
I have implemented this feature and opened a PR for it, would be grateful for a review.

**Comment by kordianbruck** [comment]
Awesome, I guess this can now be closed :)

Thanks a lot!
