### ISSUE TITLE
Crash in settings when logged out

### ISSUE THREAD

**Issue by SiKreuz** [TUM-Dev/Campus-Android#1368]
## Steps to Reproduce
When not logged in the app crashes in the settings activity.
1. Go to settings
2. Click on one sub-setting like Mensa
3. App crashes...

The following exception is thrown:
```
java.lang.NullPointerException: logoutButton must not be null
    at de.tum.in.tumcampusapp.component.other.settings.SettingsFragment.onCreatePreferences(SettingsFragment.kt:79)
```

### Environment
* Phone: OnePlus 5T
* OS version: OxygenOS 10.0.1
* TUM Campus App version: v3.9-dev
* Language: German

**Comment by kordianbruck** [comment]
> TUM Campus App version: v1

this seems fishy. Whats the actual verison? Did you compile from source? From the store?

I did some work on this in: https://github.com/TUM-Dev/Campus-Android/commit/9075be05d136ff826b290bd4104b62f8f4a13595

**Comment by SiKreuz** [comment]
Sry, forgot that. I'm working with the latest commit from the master branch.
