### ISSUE TITLE
setting to switch between weekly and daily for calendar

### ISSUE THREAD

**Issue by AW-tum** [TUM-Dev/Campus-Android#1378]
a user requested a setting to decide wether you see the calendar as weekly or as daily instead of always having to manually switch to weekly when opening the app

**Comment by kordianbruck** [comment]
Probably we can just save the setting, when switching. This seems easy enough.

**Comment by Liqs-v2** [comment]
I'm gonna pick this issue up, if thats okay.

**Comment by kordianbruck** [comment]
Thats weird, we just shouldn't run firebase in tests as all. I'd need to take a closer look, but that seems super wrong.

**Comment by Liqs-v2** [comment]
Okay thanks, for some more info on what I have tried so far in order to get this to work, check out the [pull request](https://github.com/TUM-Dev/Campus-Android/pull/1399), that I have opened for this issue.

**Comment by joschahenningsen** [comment]
fixed in #1399
