### ISSUE TITLE
Semesterbeitrag weicht 0,40€ ab

### ISSUE THREAD

**Issue by AW-tum** [TUM-Dev/Campus-Android#1380]
Der Semesterbeitrag auf der App wird mit 144,00 €, beträgt aber 144,40 €

Nichts großes, aber gab schon paar Bemerkungen von Nutzern.

**Comment by joschahenningsen** [comment]
![Screenshot_20210128-224139~2.jpg](https://user-images.githubusercontent.com/44805696/106202384-22c3ca00-61ba-11eb-8ac5-b83149bdb066.jpg)

Kann ich nicht reproduzieren. Tritt das Problem bei der aktuellen Version auf?

**Comment by AW-tum** [comment]
hmm ok
hab leider kein Android
Aber bei iOS stehts noch falsch da

**Comment by joschahenningsen** [comment]
This can be closed then I suppose.

**Comment by kordianbruck** [comment]
Yea, this is an iOS specific issue. Thanks for opening the other one.
