### ISSUE TITLE
Login not working properly

### ISSUE THREAD

**Issue by SiKreuz** [TUM-Dev/Campus-Android#1389]
## Steps to Reproduce

1. Go through the login process
2. See the error message in the end

![image](https://user-images.githubusercontent.com/48913164/115995496-d5e66880-a5db-11eb-97cc-158f0b899516.png)

## Problem

The login verification fails. So the status returned here is a verificationfail https://github.com/TUM-Dev/Campus-Android/blob/105b81fd97e4ccbf3c79e0ece1c765334743f02d/app/src/main/java/de/tum/in/tumcampusapp/component/ui/onboarding/OnboardingExtrasFragment.kt#L134

I have no idea why this happens. Sometimes a restart helps and I'm logged in, sometimes it doesn't. 
This error happens on my phone, as well as on a virtual device, so it seems to be platform independent.

### Environment
* Phone: OnePlus 5T
* OS version: OxygenOS 10.0.1
* TUM Campus App version: v3.9
* Language: German and English

**Comment by joschahenningsen** [comment]
I'm also getting this toast:
https://github.com/TUM-Dev/Campus-Android/blob/105b81fd97e4ccbf3c79e0ece1c765334743f02d/app/src/main/java/de/tum/in/tumcampusapp/component/ui/onboarding/OnboardingExtrasFragment.kt#L124

Seems to be a backend thing. @kordianbruck did you change something when experimenting with the new server setup or are there any helpful logs?

**Comment by joschahenningsen** [comment]
Apparently this is the underlying issue: 
`Uncaught Error: Class 'Crypt_RSA' not found in /app/App/Model/Device.php:47`
Full stack trace: 
```
<b>Fatal error</b>:  Uncaught Error: Class 'Crypt_RSA' not found in /app/App/Model/Device.php:47
    Stack trace:
    #0 /app/App/Modules/Api/Device.php(57): Model_Device::checkSignature('GESAEGEA...')
    #1 /app/App/Router.php(207): Modules_Api_Device::register(Object(stdClass), Object(stdClass))
    #2 /app/App/Core.php(104): Router-&gt;dispatch()
    #3 /app/Public/index.php(51): Core-&gt;run()
    #4 {main}
      thrown in <b>/app/App/Model/Device.php</b> on line <b>47</b><br />
```

**Comment by kordianbruck** [comment]
For context: backend was missing a dependency for using RSA functions.
