### ISSUE TITLE
Calendar time doesn't respect users current time zone

### ISSUE THREAD

**Issue by sobuj53** [TUM-Dev/Campus-Android#1392]
## Steps to Reproduce

1. Move to a different time zone
2. Open TUM Campus app
3. Home as well as calendar will not show event time based on current time zone. 

## Expected Result
The app should detect current time zone and show event time accordingly 
## Actual Result
App is showing event time based event's time zone.  
## Problem
Many international students are currently staying on their home country due to online lecture format. But TUM Campus app can't detect our time zone and show event time accordingly. The app would prove more productive if it can show lecture and other events time based on our current time zone instead of standard CET.  
## Suggested Enhancement :sparkles:
Please implement a feature to detect current time zone of TUM Campus app and process event time relative to that information.
### Environment
* Phone: Xiaomi mi5
* OS version: Android 11
* TUM Campus App version: v3.11
* Language: English

**Comment by joschahenningsen** [comment]
Feel free to pick it up if you want :)

**Comment by Liqs-v2** [comment]
I am picking this issue up :)

**Comment by Liqs-v2** [comment]
I have implemented a fix and opened a PR for it.

**Comment by Liqs-v2** [comment]
Fixed in #1401
