### ISSUE TITLE
Integrate artemis in app

### ISSUE THREAD

**Issue by maharajamihir** [TUM-Dev/Campus-Android#1402]
Create Plugin for Artemis in this app. Shouls be optional plugin, since its only relevant for informatics students.

**Comment by CommanderStorm** [comment]
What kind of an Plugin do you think of?

The problem, I see is, that Artemis does not offer a public API. (https://github.com/ls1intum/Artemis and https://docs.artemis.ase.in.tum.de dont mention a public API anywhere)
Thus any service would have to rely on a special, for us created API, or we would have to reverse-engeneer Artemis, which are both not ideal..
(correct me If I'm wrong)

**Comment by maharajamihir** [comment]
Hi, thanks for your reply. Maybe for the beginning one could use something like a webview as an adapter. 
https://developer.android.com/guide/webapps/webview
Not 100% sure if that works, since I dont have as much expirience with native android app development. What I love about this app is that everything is in one place, so maybe this would actually bring artemis to this place too, even though it would actually be displaykng web content. 

With Plugin I meant, that it should be optional for users to activate Artemis here, since only CS students actually use it. Maybe one can enable it in settings or so?

**Comment by joschahenningsen** [comment]
Artemis is basically a huge rest API with an angular client, building in some basic features would not be too complicated I suppose, the only problems would be:

- Users would be required to provide their tum credential to the campus app (meh). And unless they are saved, sessions would expire and constant re-logins would be required. 
- the Artemis API is not subject to any kind of semantic versioning, whatever we build could break as soon as they change something. 


@maharajamihir which kind of Artemis related features would be useful to you? Just checking your score, due dates etc. Or actually participate in exercises?

**Comment by maharajamihir** [comment]
@joschahenningsen 

Yes viewing the excercises, getting updates for due dates (maybe in the future even notifications for that), seeing stats would be enough. Maybe if possible also viewing file upload submissions.

**Comment by joschahenningsen** [comment]
Closing this because the artemis team is developing their own app now: https://github.com/ls1intum/artemis-android
