### ISSUE TITLE
ActionBar blank after dependency bump

### ISSUE THREAD

**Issue by jfoerste** [TUM-Dev/Campus-Android#1408]
10a625b185ae04063d3b319f6f75d5e51216ee69 seems to have caused a regression.

## Steps to Reproduce

1. Open any fragment via the drawer

## Expected Result
Everything appears normally.

## Actual Result
The action bar (and the drawer button) become completely blank.

## Screenshot
![](https://i.jfoe.de/KCTX)

**Comment by Liqs-v2** [comment]
Hello, I have deployed a temporary fix for now (see #1409) it is already merged into master aswell.
