### ISSUE TITLE
Room finder doesn't work

### ISSUE THREAD

**Issue by sobuj53** [TUM-Dev/Campus-Android#1413]
## Steps to Reproduce

1. Open any existing lecture schedule from calendar > click on location > tap on room on room finder > sorry something went wrong
2. Go to room finder > search any room > tap on room > sorry, something went wrong
3.

## Expected Result
The app should show the location in map or al least try to open the location with external application such as google map.

## Actual Result
The app doesn't give any feedback only shows error.

## Problem
Room finder function is broken.
## Suggested Enhancement :sparkles:
I can think of 2 possible solution to this,
1. The location should be shown within the app and have the possibility to open the location with external application such as google map
2. The app can redirect to room finder webpage eg, `https://portal.mytum.de/displayRoomMap?roomid=1260@0502&disable_decoration=yes`
### Environment
* Phone: Xiaomi
* OS version: 11
* TUM Campus App version: v3.13 
* Language: English

**Comment by jfoerste** [comment]
Might have been addressed already in #1405.

**Comment by sobuj53** [comment]
yes but the issue is not resolved

**Comment by jfoerste** [comment]
It is not yet shipped. Have you tried building the app from the current sources? App version 3.13 does not include this fix.

**Comment by sobuj53** [comment]
> It is not yet shipped. Have you tried building the app from the current sources? App version 3.13 does not include this fix.

No 😅, cause I don't know how

**Comment by joschahenningsen** [comment]
The newest version is currently being shipped to some beta users and will be released publicly if there are no major issues with the release. Shouldn't take longer than one or two weeks :)

**Comment by kordianbruck** [comment]
3.17 is going out to 100% today.

**Comment by mpmic** [comment]
Hi @kordianbruck,
Where can we find the apk? I've checked play store and I cannot see any updates.

**Comment by kordianbruck** [comment]
I think there was another button to press, that I missed. It should now be really released. Sorry about that :/

**Comment by mpmic** [comment]
It's up! Thank you for this :)
