### ISSUE TITLE
Sdk version bump issues

### ISSUE THREAD

**Issue by jfoerste** [TUM-Dev/Campus-Android#1427]
The sdk version bump in 564059be65025d9a9d1645d815409ee868e69037 broke the install and introduced a crash as some new requirements are not met.

1. LeakCanary version must be bumped accordingly, as its Manifest is outdated
2. CompileSdkVersion should propable also be bumped
3. `PendingIntent`s now require explicitly specifying `FLAG_IMMUTABLE` or `FLAG_MUTABLE`, else the app crashes

**Comment by kordianbruck** [comment]
Thanks for the report, can you take a quick look at #1428?
