### ISSUE TITLE
Navigation drawer is blank in some Activities

### ISSUE THREAD

**Issue by ctsk** [TUM-Dev/Campus-Android#1433]
## Steps to Reproduce

1. Open App & Connect to TUMOnline
2. Navigate to Chat rooms
3. Open any chat room
4. Swipe from left to open the navigation drawer

----

1. Open App
2. Open TU Film card
3. Swipe from left to open the navigation drawer

## Expected Result
See Navigation

## Actual Result
Drawer is blank

<details>
<summary>Screenshot</summary>

![scrot-drawer](https://user-images.githubusercontent.com/9384305/165911695-edcd65c4-cb4b-4fe6-b6b4-d177d19c79af.png)

</details>

### Environment
* Phone:  Pixel
* OS version: 12
* TUM Campus App version: v3.13
* Language:  English

**Comment by Bentipa** [comment]
I guess the correct solution here would be to completely disable the drawer when being inside such a child view.
