### ISSUE TITLE
News shows empty tiles

### ISSUE THREAD

**Issue by kmodexc** [TUM-Dev/Campus-Android#1438]
## Steps to Reproduce

1.  Open news

## Expected Result

Newspread FMI tile has a picture

## Actual Result

No picture
No text

### Environment
* Phone: Samsung S10+
* OS version: 12
* TUM Campus App version: v3.18-dev
* Language: EN

It opens the picture when clicked, but shows nothing in the tile. So nobody knows whats its content before one click on it.

**Comment by CommanderStorm** [comment]
Note that this works on my neigbours Device (Pixel 4a), while it does not on my (a bit ancient) Device (Samsung S8)

**Comment by kmodexc** [comment]
It seems to be a 404. The Image link returns a 404 so it doesnt load. 

This is one example: https://tumcabe.in.tum.de/File/news/newspread/bf7247e0e504035f9e601d5aa8436641.jpg

Im trying to figure out where this comes from and if its correct.

**Comment by joschahenningsen** [comment]
Probably a backend issue, looking into it

**Comment by joschahenningsen** [comment]
should be good now, can you please verify? :)

**Comment by kmodexc** [comment]
Yes works

**Comment by CommanderStorm** [comment]
I tried deleting the cache before opening this issue. After deleting the data it is fixed.
Sorry..
