### ISSUE TITLE
[Feature] Calendar notification does nothing when clicked

### ISSUE THREAD

**Issue by kmodexc** [TUM-Dev/Campus-Android#1441]
It would be nice, if it would open the location of the lecture. I would like it if it opens `nav.tum.sexy` with the location.

**Comment by CommanderStorm** [comment]
Opening in-app, if #1437 is done would be good, too :)
Going off-platform is not nessesesarily the best UX, but this is just Personal preference.
Going by the ammount of cool features that we are developing currently redirecting Off-Platform could be a good solution, until the campusapss have catched up.

However the Locations are pretty cryptic sometimes.
Does anyone have a longer samplesize of what possible values are? (for a test, how reliable we are and where we have to implement some extra logic)
