### ISSUE TITLE
kotlin-android-extensions is deprecated

### ISSUE THREAD

**Issue by kmodexc** [TUM-Dev/Campus-Android#1445]
This warning appears in the build. Does anyone know what this means and how to fix it?

```
The 'kotlin-android-extensions' Gradle plugin is deprecated. Please use this migration guide (https://goo.gle/kotlin-android-extensions-deprecation) to start working with View Binding (https://developer.android.com/topic/libraries/view-binding) and the 'kotlin-parcelize' plugin.
```

**Comment by CommanderStorm** [comment]
I can look into View Binding and kotlin-parcelise if you'd like, since I am looking at our dependencys in #1463 anyway.
(I dont know yet, if this rectifies its own PR and I will decide when I get to this 😉)

**Comment by Bentipa** [comment]
Okay that would be nice, thank you @CommanderStorm.
