### ISSUE TITLE
Reviewing function about lectures

### ISSUE THREAD

**Issue by yujinkimmn** [TUM-Dev/Campus-Android#1446]
## Problem
After we log in the the app, and In the category 'My Lectures', we can see the list of lectures that we are taking in current semester. When we click on of them, there are informations about that lecture, but there is no way to know about the experience from other students who already took this lecture.

### Environment
* Phone: Android
* TUM Campus App version: v1
* Language: kotlin 

### Expected Result
By adding reviewing functions, students can check the review from other students about specific course, and also can write some reviews.

**Comment by kordianbruck** [comment]
I like the idea, but we need then some sort of moderation. Students will write "mean" things and while that might be their honest viewpoint, we will have to take responsibility for any content delivered in the app. This is why this was infeasible in the past.

**Comment by CommanderStorm** [comment]
Actually, that is what the lecture evaluations are for.
When you participate, you even see how the average of other students voted.
I don't think we can get better than this from a statistics perspective.
Publishing those islegally impossible, sadly.

I am closing this. We can reopen, if you have other input.
