### ISSUE TITLE
Delete the seconds of each lecture in Lecture Appointment

### ISSUE THREAD

**Issue by yujinkimmn** [TUM-Dev/Campus-Android#1453]
## Problem
In My Lectures > Lecture Appointment, we don't need the seconds of each lecture.

## Suggested Enhancement :sparkles:
<My Lectures> In the 'Lecture Appoinments' page, delete the seconds of each lecture.

**Comment by kordianbruck** [comment]
https://cal.bruck.me/ does that - maybe we should adapt the proxy to work with the app as well, but it'd need to be an opt-in feature.
