### ISSUE TITLE
Reconsider Chat for large courses

### ISSUE THREAD

**Issue by CommanderStorm** [TUM-Dev/Campus-Android#1455]
## Steps to Reproduce

1. Go to the chat of the SVV
2.
![20220606_090618](https://user-images.githubusercontent.com/26258709/172112835-d9270eb9-fccd-46c8-be79-b11f6243e5f2.jpg)

## Expected Result
Not pinging 5k People at 3am

## Actual Result
5k People are pinged at 3am

## Problem
The student council uses courses to enshure, that all students have the requisite blockers in their calendars and to make shure that this is present in everyones schedule.
This does however mean, that at least one course with a lot of participants does exist.

## Suggested Enhancement :sparkles:
We could:
- Disable chats with more than 500p. This limit is intentionally low, to lower the spam inpact one person can have.
Even the largest informatics lectures only have about ~400 Participants.
- Disable chats alltogether. I have not seen a good use for this feature in my 3 years. This kind of usage must be rare..
- Make the `leave chatroom` button more prominent.
  Currently this one is kind of burried in the top right corner of my device. It would be nice to have this a bit more prominent

### Environment
* Phone: Galaxy S8
* OS version: Android 9
* TUM Campus App version: 3.18
* Language: German

**Comment by kordianbruck** [comment]
>  I have not seen a good use for this feature in my 3 years. This kind of usage must be rare.

I'd be interested in why - too many other alternatives these days?

**Comment by CommanderStorm** [comment]
> I'd be interested in why - too many other alternatives these days?

The gist is, that normal chat platforms work better (more features like Images/moderation/reactions/... , less bugs like #1277) and have a higher user-adoption rate.
For example the SVV course only has 5k people.. we are 48k Students, so this penetration rate is kind of not good.
