### ISSUE TITLE
Allow to open Roomfinder location in other apps like Google Maps

### ISSUE THREAD

**Issue by PiotrKedra** [TUM-Dev/Campus-Android#1456]
## Problem

I think it would be handy for users to allow them to open the Google Map app from Roomfinder. Why? For instance, a user could open a lecture location in Google Maps for car navigation. What is more, we could also allow users to open the location in other apps like MVV or Uber.

## Expected Result

Alongside Roomfinder Screen at the top, there is a menu where users can choose to open a location in Google Maps/MVV/Uber ...

**Comment by CommanderStorm** [comment]
Related issues in another Project of ours:

https://github.com/TUM-Dev/navigatum/issues/87

MVV/Uber might be a good strech-goal for https://github.com/TUM-Dev/navigatum/issues/86

**Comment by PiotrKedra** [comment]
So I guess it is better to implement it in navigatum project, rather than here?

**Comment by CommanderStorm** [comment]
No, my comment was just indendet to group related issues together across different projects.
This issue right where it belongs, This should not need any support from any backend.
(Note that the campusapps are not yet using Navigatum https://github.com/TUM-Dev/Campus-Android/issues/1451)

But this feature will be done at https://nav.tum.sexy sooner, as making changes to a website is easier.
See https://github.com/TUM-Dev/navigatum/pull/136 for the discussion on what/how we want to implement this.

Btw, I saw that you have a some Kotlin experience..
Would you like to contribute on this feature? I am currently a bit strapped for time if I am honest..

**Comment by PiotrKedra** [comment]
You mean #1451? I am currently working on #1457, but when I finished with this, then I might have a look at migration to NavigaTUM 🙂
