### ISSUE TITLE
 Add the opening hour information on the mensa page

### ISSUE THREAD

**Issue by yujinkimmn** [TUM-Dev/Campus-Android#1459]
## Problem
<img width="237" alt="스크린샷 2022-06-29 21 37 09" src="https://user-images.githubusercontent.com/75295578/176521648-b4446bae-2ce9-44e8-a6c9-4edef3c4d9fb.png">
In current cafeteria category page, the time information for each mensa is too limited.
It's only like "Closed 14:00".

## Suggested Enhancement :sparkles:
By editing this part, more information can be added related to opening / closing time for each mensa.
Like "Open 11:00 - Closes 14:00" according to the current time.

**Comment by alexanderstephan** [comment]
Nice idea 👍 But be careful with merge conflicts with https://github.com/TUM-Dev/Campus-Android/pull/1422, which might work on similar files.
