### ISSUE TITLE
Barrier-free facilities are not loaded

### ISSUE THREAD

**Issue by PiotrKedra** [TUM-Dev/Campus-Android#1473]
## Steps to Reproduce

1. Open Menu
2. Click Barrier-free Information
3. Chose Facilities

## Expected Result

The app shows a list of barrier-free facilities.

## Actual Result

The app does not load barrier-free facilities and a blank screen is displayed. Sometimes instead of a blank screen "Unknow error" was shown with the "Retry" button, and then facilities get "sometimes" loaded. Idk why it has such strange behaviour.

## Problem

On the current master branch, the app does not display the list of barrier-free facilities and the below error appears in the logs. However, the current version of the app 3.18 that is on the Googe Play Store sometimes works, but not always ... ;D

## Logs

W/System.err: android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
W/System.err:     at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:9806)
W/System.err:     at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:1890)
W/System.err:     at android.view.ViewExtImpl.hookRequestLayout(ViewExtImpl.java:509)
W/System.err:     at android.view.View.requestLayout(View.java:25905)
...

### Environment
* Phone: One Plus 9 Pro
* OS version: Android 12
* Language: English

**Comment by PiotrKedra** [comment]
Yeah, I just reported it, feel free to take it ^^

**Comment by Bentipa** [comment]
Closed via #1474
