### ISSUE TITLE
Enhance UX for TUFilm ViewPager

### ISSUE THREAD

**Issue by Bentipa** [TUM-Dev/Campus-Android#1476]
## Steps to Reproduce

1. Open TU-Film Card
2. Do not recognize you can swipe left & right

## Problem
It might not be intuitive for the users that you can swipe to the left and right to switch between movies

## Suggested Enhancement :sparkles:
Either we add a preview of the next and last item:
<img src="https://user-images.githubusercontent.com/11789478/178519393-55d16ee7-64f8-4d12-b894-d8f447c75931.png" width="250px"/>

Or we add an overlay on first open of the view that shortly shows that you can swipe to the left and right.
Example:
![image](https://user-images.githubusercontent.com/11789478/178519650-fabf9e2c-7122-4058-bdb2-6a2b0aca064c.png)

**Comment by Bentipa** [comment]
@kordianbruck @CommanderStorm @joschahenningsen maybe you guys have an opinion on this? :)

**Comment by joschahenningsen** [comment]
I didn't know this was possible either 😀
Option one seems quite intuitive!

**Comment by Bentipa** [comment]
@CommanderStorm maybe another opinion before I work on it?

**Comment by CommanderStorm** [comment]
> I didn't know this was possible either :grinning: Option one seems quite intuitive!

I agree with joscha.
