### ISSUE TITLE
Translate names of menu into English

### ISSUE THREAD

**Issue by yujinkimmn** [TUM-Dev/Campus-Android#1477]
## Problem
<center><img src= "https://user-images.githubusercontent.com/75295578/178926414-3992e908-4072-4b9d-8725-ac8df03dd507.png" width="300" height="600"></center>
In Cafeteria category, all of the names of menus in mensa are in German. I wonder the possibility of translating into English as well as German. 

## Suggested Enhancement :sparkles:
By adding translating function, I would like to make it more convenient.

**Comment by CommanderStorm** [comment]
This should be possible, once #1370 is done, since this new API supports this Feature
There are some blocking bugs though in that issue. If you'd like to help debug those help is always welcome.
That PR has been open for way too long.
