### ISSUE TITLE
Edit formatFutureTime function in DateTimeUtils.kt

### ISSUE THREAD

**Issue by yujinkimmn** [TUM-Dev/Campus-Android#1478]
## Problem
"formatFutureTime function" provides users with calculated time 'diff' between the parameter 'time' and current time. And according to the if-else statement, it provides relative left times. 
But when using the app, it could be more convenient to show more detailed diff time, not only for below 60minutes, but also for below a few hours. 

### Current Codes
<img width="665" alt="스크린샷 2022-07-17 21 39 40" src="https://user-images.githubusercontent.com/75295578/179422121-cb94271e-d462-44f0-94af-4fe5139a453a.png">

First, to show more precise left time for users, I changed this function like this.
<img width="665" alt="스크린샷 2022-07-17 21 43 13" src="https://user-images.githubusercontent.com/75295578/179422197-469e1051-29b0-4019-8380-911e26ae26d5.png">

## Suggested Enhancement :sparkles:
But this doesn't provide the every updated minutes, so I want to edit this function to make round up or down the diff minutes to hours so that it could be more precise than before and also doesn't need to be updated every minute.

**Comment by Bentipa** [comment]
Hey,

I do not totally understand what your suggested enhancement is.
Could maybe provide some examples and how they would be handled now and what you want it to do?

**Comment by CommanderStorm** [comment]
@Bentipa this issue is probably a result of #1461. 
I think that updating the function regularly is a better solution, though…

I am not convinced that truncating and rounding the minutes into hours is a good thing to do, since it would just be a bodge in my oppinion.

**Comment by Bentipa** [comment]
Ahh okay t hanks @CommanderStorm for the heads-up!

I guess we are also updating the train departure times every second, so updating the opening times here in minutes would be better in my opinion too:)

**Comment by yujinkimmn** [comment]
> Ahh okay thanks @CommanderStorm for the heads-up!
> 
> I guess we are also updating the train departure times every second, so updating the opening times here in minutes would be better in my opinion too :)

I see! I understood what you guys said. Can I just delete this issue?
