### ISSUE TITLE
`JobIntentService` API Deprecation

### ISSUE THREAD

**Issue by CommanderStorm** [TUM-Dev/Campus-Android#1485]
We currently use the `JobIntentService` for example for getting the Users Location  [app/src/main/java/de/tum/in/tumcampusapp/service/GeofencingRegistrationService.kt](https://github.com/TUM-Dev/Campus-Android/blob/master/app/src/main/java/de/tum/in/tumcampusapp/service/GeofencingRegistrationService.kt)

## Problem
The `JobIntentService` API is deprecated and has problems like https://issuetracker.google.com/issues/63622293

## Suggested Enhancement :sparkles:
The `JobIntentService` API is deprecated and should be replaced with `WorkManager`

## Aditional Information
I think that this change is too large for #1468

**Comment by zaghdaneh** [comment]
I started working on this issue. I Will be trying to replace everything with `WorkManager` as suggested.
