### ISSUE TITLE
`startActivityForResult` is Deprecated

### ISSUE THREAD

**Issue by CommanderStorm** [TUM-Dev/Campus-Android#1486]
We currently use `startActivityForResult` and `onActivityResult` for example for joining chatrooms. 

## Problem
The `startActivityForResult` and `onActivityResult` are deprecated

## Suggested Enhancement :sparkles:
From the Deprecation Note:

> This method has been deprecated in favor of using the Activity Result API which brings increased type safety via an `ActivityResultContract` and the prebuilt contracts for common intents available in `androidx.activity.result.contract.ActivityResultContracts`, provides hooks for testing, and allow receiving results in separate, testable classes independent from your fragment.
Use `#registerForActivityResult(ActivityResultContract, ActivityResultCallback` passing in a `StartActivityForResult` object for the `ActivityResultContract`.
    
## Additional Information
I think that this change is too large for #1468

**Comment by cchigo** [comment]
hi. i would like to work on this issue
