### ISSUE TITLE
[BUG] Grade Bar Chart is scaled wrongly

### ISSUE THREAD

**Issue by LorenzNickel** [TUM-Dev/Campus-Android#1505]
**Describe the bug**
The Bar Chart in the Grades Fragment has a weird scaling on the x-axis (0 - 41 instead of 1.0 - 5.0).
![image](https://user-images.githubusercontent.com/29959150/181859435-aeb104ee-bfa2-4f2c-a1bd-188e86d623ad.png)

**To Reproduce**
1. Go to "My Grades"
2. Switch to the Bar Chart

**Expected behavior**
The scaling on the x-axis should be 1.0 - 5.0.
![image](https://user-images.githubusercontent.com/29959150/181860094-5b489f63-36c7-4c07-85d9-3ea063f71883.png)
(I didn't manage to get it completely right, but you probably understand what I feel it should look like)

**Smartphone:**
* Phone: Samsung M51
* OS version: Android 12
* Language: English

**Additional considerations:**

* I don't understand why the bar-values (labels) are formatted as X.0 where X represents the count/amount of such grades. As you can see in the screenshot above, I would suggest switching to just X (or maybe even show the value (like 1.3) instead of the amount).
* I feel like B ratings can be skipped in the graph. I don't see a point in showing them in the bar chart, especially as representing them as something worse than 5.0 is not accurate. One could even think about also removing them from the pie chart, but especially in the bar chart, they don't make much sense.
* "Consider credits and weights in the diagram" ([here](https://github.com/TUM-Dev/Campus-Android/blob/4f75a327aa88a1773ce468aab0743923284b6406/app/src/main/res/layout-land/fragment_grades.xml#L30) and [here](https://github.com/TUM-Dev/Campus-Android/blob/4f75a327aa88a1773ce468aab0743923284b6406/app/src/main/res/layout/fragment_grades.xml#L74)) should not be checked by default. I think activating this feature by default is confusing to most users, especially when they have not weighted their grades (yet). 
![image](https://user-images.githubusercontent.com/29959150/181860006-7d9760cd-6dcc-4faf-8512-971ce5eb8c9d.png)

**Comment by tobiasjungmann** [comment]
Thanks for the detailed issue for the new feature! :D I will fix the labels on the diagram, I haven't noticed them before and they obviously don't make sense right now. 
Initially, all exams have the same weight (1) and credits (5). Therefore, these values are uninteresting in the diagram (once it has a reasonable axis label) until the user actively alters an exam. In my opinion, this change should then be taken into account directly in the diagrams.
