### ISSUE TITLE
[Feature] Open parent location details by clicking on them

### ISSUE THREAD

**Issue by PiotrKedra** [TUM-Dev/Campus-Android#1508]
## Description
Allow parent location details to be opened by clicking on parent names in the new navigation details screen. The screenshot shows precisely what I mean by parent names. It could work similarly to how it is implemented on NavigaTUM website https://nav.tum.sexy/building/mi

<img src="https://user-images.githubusercontent.com/23524945/183645290-71802920-2810-47f9-a122-e890915cd1f0.jpeg" alt="pic 1" width="300"/>

**Comment by ctsk** [comment]
I have this in the works :)
