### ISSUE TITLE
[BUG] App crashes when using search function

### ISSUE THREAD

**Issue by wjon-tum** [TUM-Dev/Campus-Android#1517]
**Describe the bug**
When clicking on the search button in the navigation drawer (second from top), the application closes every time with standard error message.

**To Reproduce**
1. Go to the navigation drawer on the left side
2. Click on the search button (in German labeled "Suchen")
3. See error

**Expected behavior**
I can search for persons, rooms, or whatever

**Smartphone (please complete the following information):**
* Phone: Samsung Galaxy A20e
* OS version: Android 11
* Language: German

**Comment by CommanderStorm** [comment]
I can't reproduce this on my phone (Samsung Galaxy A53)…

Are you by any chance able to get access to the crash log? What error message are you seeing?

**Comment by wjon-tum** [comment]
Alas, I have no clue where to find the crash logs, but in 'Additional information' in 'about the app' it sais 'Bug reports true'. The error message is just the standard system message which shows every time that an app crashes..

**Comment by kordianbruck** [comment]
Could be this one: 
![image](https://github.com/TUM-Dev/Campus-Android/assets/298860/883b34cd-a4d4-4f99-b77c-8ac532d659f6)
