### ISSUE TITLE
[BUG] Time to cafeteria (Mensa) closing is off by one (hour)

### ISSUE THREAD

**Issue by just-max** [TUM-Dev/Campus-Android#1521]
**Describe the bug**
Message that shows how long until the cafeteria closes is off by one hour.

**To Reproduce**
1. At 11:06, go to the cafeteria page for the Mensa Garching
2. Look at the "Closes in..." text
3. Says "in 3 h 54 minutes"

**Expected behavior**
Should say "in 2 h 54 minutes"

**Smartphone (please complete the following information):**
* Phone: Samsung Android device
* OS version: Samsung Android 11
* Language: English

**Comment by just-max** [comment]
Also, the translation of "um 14:00" should be "at 14:00", not "on 14:00", unless that's a British English thing.

**Comment by xarantolus** [comment]
I can see the same bug on my device and have looked into this a bit. It appears that in DateTimeUtils a new DateTime is created with the wrong timezone (local timezone UTC+1) and then formatted (so time diff 1h45m becomes 2:45 o'clock, being formatted as 2 h 45 min). When changing to UTC it appears to work, but I need to do more testing to confirm this. 

Will create a PR soon
