### ISSUE TITLE
[BUG] 'Back' button missing from toolbar in lecture details view

### ISSUE THREAD

**Issue by ctsk** [TUM-Dev/Campus-Android#1533]
**Describe the bug**
When viewing lecture details, there is no "back" button in the toolbar.

**To Reproduce**
1. Go to My Lectures
2. Click on <Any lecture>
3. See error: There's an empty toolbar with no back button.

**Expected behavior**
Either no toolbar or a toolbar with a back button visible

**Screenshots**
![image](https://user-images.githubusercontent.com/9384305/201728613-df483390-00a8-41e0-9493-b70516cf16f8.png)

**Smartphone (please complete the following information):**
* Phone: Pixel 3a
* OS version: 12
* Language: German

**Additional context**
Gesture navigation works

**Comment by Marius1501** [comment]
Could you assign me to this issue? I would like to work on this. 😄
