### ISSUE TITLE
[Feature] Show current lecture in progress

### ISSUE THREAD

**Issue by VictorHartman** [TUM-Dev/Campus-Android#1540]
The next lecture block is useful to know where my next class is. However when I am late, even just one minute, and I look on my phone this info is no longer available.

The solution is to show the current class in progress. This way I will know where I am supposed to be when I am delayed.

**Comment by xarantolus** [comment]
I'm interested in implementing this change.
I experimented by displaying all lectures that have not yet ended (which will then show the currently in progress lecture), but I'm not sure if that's the best solution (because then at the end of a lecture, it will still show the current lecture).
Maybe it makes sense to display the current lecture if the current time is before or up to 15/30 minutes after the start time?

**Comment by CommanderStorm** [comment]
We could also display multiple lectures and have 15 m overlap where two lectures take place (assuming overlap).
This does also solve the problem that sometimes lectures overlap (one online+recorded, one not).

**Comment by VictorHartman** [comment]
What I had in mind was to display two cards. One for currently in session and one for coming up.

**Comment by xarantolus** [comment]
I have [tried out](https://github.com/TUM-Dev/Campus-Android/compare/master...xarantolus:TUM-Campus-Android:feature/lecture-card-time) splitting the lectures into in progress/upcoming (or by next lectures that start within 15 minutes of each other as fallback) and then displaying multiple in the card without expanding.
I also tried more complex criteria, showing multiple overlapping lectures etc, but I feel like often there's a case where one could argue that something is behind the "expand" button when it should not be.
I feel like it would make sense to just display up to 4 lectures of the current day (the same day as the first lecture) that haven't ended. That way, the card gives you a quick overview of the rest of the day, including currently ongoing and overlapping lectures. The expand button would then only show lecture that are not today.
So the question is whether we want more complex logic that tries to minimize the number of lectures shown, or we just take a bit more screen space and show e.g. up to 4 of the next items (if they are today, rest behind expand button).

**Comment by CommanderStorm** [comment]
Sounds reasonable to me
