### ISSUE TITLE
[BUG] Mensa feature is not working 

### ISSUE THREAD

**Issue by JudithBernett** [TUM-Dev/Campus-Android#1552]
**Describe the bug**
The mensa plans are not showing up anymore. Instead, an empty page is displayed. 

**To Reproduce**
1. Go to Mensen
2. Click on any Mensa of your choice
3. An empty page is displayed

**Expected behavior**
The mensa menu of the day is displayed.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/38618495/211269176-c359eed3-f276-4e03-9208-bce2bc2f0034.jpeg)

**Smartphone:**
* Phone: Google Pixel 6
* OS version: 13
* Language: German

**Comment by alex-d13** [comment]
Could it be because there is no Speiseplan uploaded for today to the mensa websites?

**Comment by tobiasjungmann** [comment]
Thanks for reporting! Currently, there is no data from the Stuwerk -> no data in eat api -> no data in the app. Once the stuwerk published their new meal plan it should work again
