### ISSUE TITLE
[BUG] changes in grading of an exam doesn't reflect in "meine Noten" 

### ISSUE THREAD

**Issue by jonasfeld** [TUM-Dev/Campus-Android#1559]
**Describe the bug**
If you get a grading on an exam and automatically load it into the "meine Noten" section of the campus app (pull down to refresh), then after a second correction your grading changes (also shows in tum online) - even after multiple times of refreshing, it doesn't show the new grade. 

**To Reproduce**
1. Write exam
2. Get notified that your grades are there
3. Go to "Meine Noten" 
4. Pull down to refresh
5. They had an error in the correction of the exam so they correct that
6. Get a better grade for that exam
7. See 2.
8. Go to "Meine Noten" 
9. Change in grade doesn't reflect! 

**Expected behavior**
Show the new grade. 

**Smartphone (please complete the following information):**
* Phone: Samsung Galaxy A70
* OS version: Android 11
* Language: German
* App version: 4.1

**Additional context**
If that matters, the exam I'm talking about is EIDI.

**Comment by tobiasjungmann** [comment]
Thanks for reporting! The grade is currently only stored once and never updated. We did not though about changing a grade after it was published. I'll fix it. Congratulations to the better grade :D
