### ISSUE TITLE
[BUG] Mixed languages

### ISSUE THREAD

**Issue by Garfield96** [TUM-Dev/Campus-Android#1585]
**Describe the bug**
While the app language is set to English, some pages show the title in German (e.g. "Lecture Information" or "About the app") (see screenshot). Other elements on these pages use the correct translation, e.g. the "Lecture Appointments" button.

**To Reproduce**
1. Set language to English.
2. Go to "Lecture Information" or "About the app"
3. See incorrect title

**Expected behavior**
All elements should use the same language (except for elements fetched from external sources, like TUMonline).

**Screenshots**
<img src="https://github.com/TUM-Dev/Campus-Android/assets/15248220/c66da90f-da41-4177-8339-631f7add7484" width="300">

**Smartphone :**
* Phone: Redmi Note 8 Pro
* OS version: 11 RP1A.200720.011
* Language: German

**Additional context**
Could be related to switching the language (maybe some caching issue).

**Comment by SecretIdetity** [comment]
possibly also the title in the about section

![Screenshot_2023-06-12-14-03-52-248_de.tum.in.tumcampus~2.jpg](https://github.com/TUM-Dev/Campus-Android/assets/66640362/732b1ae7-a7cc-440d-a2e1-6eb79a0c2ae6)
