### ISSUE TITLE
[Feature] Add the Bildungscampus Mensa in Campus Heilbronn

### ISSUE THREAD

**Issue by PermissionError** [TUM-Dev/Campus-Android#1623]
**Is your feature request related to a problem? Please describe.**
The App currently does not include information about the Bildungscampus Mensa at Campus Heilbronn.

**Describe the solution you'd like**
The Studierendenwerk Heildelberg runs the Bildungscampus Mensa, and the opening times and daily menus are available on their website. It should be feasible to pull this from the website or their API directly if there is one, and add it in a similar fashion to the other Mensas. Additionally, the app should be able to use the existing location feature to automatically display the Heilbronn Mensa if the user is in Heilbronn.

**Describe alternatives you've considered**
There is a separate "Mein Bildungscampus" app that provides public transport timetables and parking information for Campus Heilbronn. However, the Mensa is not covered and that App is not open source, therefore contribution is not possible.

**Additional context**
I am happy to contribute this feature myself, but may take some time as I learn the structure of the app source code.

**Comment by tobiasjungmann** [comment]
The meal plans are currently queried by the [eat-api](https://github.com/TUM-Dev/eat-api). Every canteen provided in this api will automatically be included in this app. It would be great if you could add it there! Please open the same issue there. The corresponding codebase is a bit smaller too :D

**Comment by PermissionError** [comment]
Great, thanks for the pointer!
