### ISSUE TITLE
Compare Grades with other students

### ISSUE THREAD

**Issue by kordianbruck** [TUM-Dev/Campus-Android#186]
Ich habe vor kurzem von dem Service "GradeView" im Internet gehört, wo man seine Noten eintragen kann und auch innerhalb des Studiengangs die Möglichkeit hat anonym Vergleiche zu anderen Kommilitonen aufzustellen. 
Außerdem gibt es eine Verknüpfung mit Unternehmen, welche individuelle Jobangebote zusenden können usw..

Vielleicht wäre etwas Ähnliches oder eine Integration von GradeView in die App möglich, wenn die Notenverwaltung wieder funktioniert.

**Comment by thellmund** [comment]
Can this be close, @kordianbruck?
