### ISSUE TITLE
Wecker jeden Tag automatisch stellen / Smart Alarm

### ISSUE THREAD

**Issue by kordianbruck** [TUM-Dev/Campus-Android#188]
Wecker jeden Tag automatisch x Minuten vor der ersten Vorlesung stellen.
x ggf. automatisch erhöhen,
- falls Einträge im MVV-Ticker http://www.mvg-mobil.de/Tickerrss/CreateRssClass
- falls Staumeldungen zwischen aktueller Position und Garching, Forschungszentrum
- falls aktuelle Fahrtzeit nach Garching, Forschungszentrum die übliche Fahrtzeit um mehr als 10% übersteigt

**Comment by qa-mhesse** [comment]
Done in #292

**Comment by foreverigor** [comment]
Wurde aus dem Wecker nichts ? Oder warum sehe ich diese Funktion nicht im Code ? :(

**Comment by pfent** [comment]
@foreverigor Der Wecker wurde mal implementiert, aber damals hatte das Team beschlossen statt kleiner, getrennter PullRequests einen Großen zu machen.
Leider waren in dem PullRequest auch einige Dinge dabei, die so nicht bereit waren eingesetzt zu werden, u.a. da die TUM moodle API nicht öffentlich zugänglich ist. Wir hatten uns damals dann entschlossen diesen PR merge wieder zu reverten.

Ich glaube niemand ist bisher dazu gekommen, die relevanten commits in #292 herauszusuchen und die zu cherry-picken. Wenn du dazu Zeit uns Lust hast, immer gerne. Diesmal bitte in kleinen, übersichtlichen PRs :)

**Comment by foreverigor** [comment]
Ok, also kann ich dann probieren, den Code dort zu finden und den Wecker einzeln zu implementieren ? 
Haben sich die Android-APIs für Wecker geändert, wenn es die überhaupt gab ?

**Comment by pfent** [comment]
Das wäre super! Am besten nach "SmartAlarm" oder einfach nur "Alarm" in den diffs suchen.

Android APIs sollten weitestgehend stabil geblieben sein, wenn wir für neuere Geräte nochmal extra code brauchen können wir uns das gerne zusammen nochmal anschauen

**Comment by foreverigor** [comment]
Okay, dann schau ich mir das an. 
Noch ne Frage – muss man eig. jedesmal einen neuen Token generieren, wenn man die App debuggen will ?

**Comment by pfent** [comment]
Nein, in der Regel solltest du pro Gerät nur einmal einen Token erstellen müssen. Der sollte dann einmal in den SharedPreferences hinterlegt sein und sofern du die app nicht deinstallierst sollte der da auch bleiben.
