### ISSUE TITLE
Moodle integration

### ISSUE THREAD

**Issue by kordianbruck** [TUM-Dev/Campus-Android#229]
Wanted by many. 

Check feasibility...

**Comment by kordianbruck** [comment]
@Carlinho89 @arash-a2k @enricogigantiello will work on this issue together

**Comment by arash-a2k** [comment]
Done!

**Comment by nilstk** [comment]
In discussion with ITSZ administrators as well as Moodle administrators the following idea was discussed: 
- Moodle/Shibboleth Login via WebView with Username/Password (save pw preferred)
- gathering of the sesssion id for further actions
- automatic login and session receiving in the future (hide it from user)

**Comment by nilstk** [comment]
Advanced idea: Use extention in Moodle to gain token that is valid for several months. https://moodle.org/plugins/view/local_mobile
Assignees: please contact Kordian or Nils

**Comment by kordianbruck** [comment]
Currently we are waiting for the Moodle team to implement some way of authentification and also to activate the APIs. All work from the team is currently stashed in the feature-moodle branch

**Comment by sebmarste** [comment]
From: Sebastian Stein <steins@in.tum.de>
Sent: 18.05.2017 15:29
Subject: Moodle Mobile Apps
Hallo
 
ich entwickle momentan (im Rahmen des Android Praktikums) an der Tum Campus App. Ist es möglich  zum Beispiel die offizielle MoodleApp mit moodle.tum.de zu verbinden? Wir würden gerne eine einfache Moodle Übersicht in unsere App einbauen und benötigen dazu die gleichen Schnittstellen, die auch die offizielle App nutzt. 
Nach meiner Recherche müsste hierzu der Mobile Service aktiviert sein (https://docs.moodle.org/20/de/Mobile_Webservices) und das Moodle Mobile additional features Plugin installiert sein, damit auch der Shibboleth Login funktioniert (https://docs.moodle.org/33/en/Moodle_Mobile_additional_features).
Ist das der Fall oder wäre es möglich das so einzustellen?
 
Vielen Dank,
 
Sebastian Stein

**Comment by sebmarste** [comment]
From: Support für Moodle <lms-support@tum.de>
To: Sebastian Stein <steins@in.tum.de>
Sent: 18.05.2017 18:09
Subject: Re: Moodle Mobile Apps [TUM#2017051810007473]
Sehr geehrter Herr Stein,

danke für die Nachfrage.
Aktuell bieten wir für TUM-Moodle keinen Support für die Mobile App an, daher sind die entsprechenden Schnittstellen auch nicht freigeschalten/installiert.

Leider können wir die Funktionalitäten aus Ressourcengründen und dem zu erwartenden Test- und Supportaufwand auch in den kommenden Monaten nicht bereitstellen.

Mit freundlichen Grüßen / Best regards,
Ihr / Your IT-Support Team
Dr. Matthias Baume
(Moodle-Projektleitung)
----------------------------------------------
IT-Support der TU München
----------------------------------------------

**Comment by kordianbruck** [comment]
So no moodle APIs. I guess we have to proceed with the HTML parsing then.

**Comment by kordianbruck** [comment]
Closing this issue, till the TUM decides to add API support. The HTML parsing was a mess.
