### ISSUE TITLE
Hiding certain LVs from Calendar

### ISSUE THREAD

**Issue by JohannesAck** [TUM-Dev/Campus-Android#408]
Hi, this is more of a feature-request than an issue, but it would be really cool if you could hide certain LVs from calendar. 
I'm an EE student and signing up to some Tutorübungen leads to 10 extra "lectures" every week, sometimes 3 or more at the same time, making the calendar very cluttered. It would be really nice to be able to hide them.

Thanks a lot,
Johannes

**Comment by kordianbruck** [comment]
@JohannesAck thanks for the suggestion. It is definitely do able, but not for the next release. Maybe in the future.

**Comment by JohannesAck** [comment]
Yes, it's not really urgent. Thank you.

**Comment by kordianbruck** [comment]
![](https://app.tum.de/File/feedback/2c243ce3-57f5-42bd-b41d-a6e948fa32da/0.png)

**Comment by jacqueline8711** [comment]
- [x] Group events that are shown multiple times due to multiple locations #1124 
- [ ] let user hide any event (or location), only once or for the rest of the semester (e.g. user only wants to see the room that they always go to)

**Comment by kordianbruck** [comment]
> let user hide any event (or location), only once or for the rest of the semester (e.g. user only wants to see the room that they always go to)

Its fine, if we just have a simple hide/show, for all lectures. No need for additional logic for "rest of the semester". The current handling of showing all rooms is also fine - no need to have this more detailed.

**Comment by kordianbruck** [comment]
![screenshot_20181031-095626_campus](https://user-images.githubusercontent.com/298860/47777405-f8da7f00-dcf4-11e8-9f8a-e0b308ff3836.jpg)
![screenshot_20181031-095653_samsung_experience_home](https://user-images.githubusercontent.com/298860/47777406-f9731580-dcf4-11e8-97a4-3401728a3f27.jpg)

User feedback for 2.3 says grouping is not reliable...

**Comment by jacqueline8711** [comment]
Closing for now
