### ISSUE TITLE
Let user choose their default campus in a card

### ISSUE THREAD

**Issue by pfent** [TUM-Dev/Campus-Android#412]
Probably avoids a lot of confusion about the default campus and is probably a pretty good guess

**Comment by kordianbruck** [comment]
Faculty has been removed, so this is no longer possible. I would vouch for a selection in the mensa card, the first time it is shown.

**Comment by foreverigor** [comment]
I'd say this makes sense. But isn't the Campus also used in public transport navigation?

**Comment by kordianbruck** [comment]
@foreverigor yes, it is used in the mvv card/widget/activity - it should really stop us tho?

**Comment by kordianbruck** [comment]
One can now choose their mensa that should be displayed. So that should fix this as well, as most people just wanted a specific mensa.
