### ISSUE TITLE
Get rid of hard coded opening hours

### ISSUE THREAD

**Issue by kordianbruck** [TUM-Dev/Campus-Android#491]
Currently all opening hours are hardcoded inside the `locations.csv` - this is really bad.

Need to implement an API endpoint and redo the manager.

**Comment by arisun** [comment]
Hi I would like to contribute on this issue. Is the issue  still open ?

**Comment by kordianbruck** [comment]
@arisun yes! We still have that ugly CSV in the assets folder. 

We would love to have it replaced by a API method on our server. Should I set this up for you?

**Comment by zepatrik** [comment]
Someone working on this should also add the possibility to have separate opening hours during the semester and during the semester break.

**Comment by jacqueline8711** [comment]
@i-walker Are you still planning on implementing this? The first step being the usage of the endpoint https://app.tum.de/Api/openingtimes

**Comment by kordianbruck** [comment]
@jacqueline8711 I think he is currently traveling, but will be back by the end of the week. Let us give him some more time.

**Comment by i-walker** [comment]
Can someone help me with the Apiclient I can't find it ?
