### ISSUE TITLE
Add Profile Switch

### ISSUE THREAD

**Issue by kordianbruck** [TUM-Dev/Campus-Android#656]
Users can be one of three:
* Student
* Employee
* Alumni

We should add a switch icon in the drawer at the top. This should reflect the prices shown in the mensa. During setup one should also be able to select ones profile. We can utilize the call to the TUMonline my endpoint, that returns the tokens User ids for each of those profile (if they exist) to only show valid options. [Employees that are not students - etc]

**Comment by jacqueline8711** [comment]
We're already changing the menu for users who are employees only, but we should still add automatic initial cafeteria price selection.
