### ISSUE TITLE
Chat: no notification when app is open but different activity

### ISSUE THREAD

**Issue by kordianbruck** [TUM-Dev/Campus-Android#784]
Open the App and leave it on the main screen. Use a second smartphone to send a message in one of the joined rooms. Nothing happens.

Actually there should be a notification, just as when the app is close / background.

**Comment by jacqueline8711** [comment]
This doesn't seem to be an issue anymore.
I get a notification no matter if I am in the app (any screen, also when in different chat room) or not. When I am in the right chat room the message is shown immediately and no notification is displayed.

**Comment by kordianbruck** [comment]
@jacqueline8711 thanks for checking!
