### ISSUE TITLE
Optimize for tablets

### ISSUE THREAD

**Issue by DreierF** [TUM-Dev/Campus-Android#88]
On 10" tablets and 7" in landscape orientation show two pane layout, replacing navigation drawer.
Similar to http://developer.android.com/design/media/multipane_view_tablet.png

**Comment by thellmund** [comment]
This would require refactoring all top-level activities (those that can be reached directly via the navigation drawer) into fragments (#843).

**Comment by joschahenningsen** [comment]
Closed due to inactivity (also there was quite a bit of redesign since 2014 :D)
