### ISSUE TITLE
Use architecture component's WorkManager

### ISSUE THREAD

**Issue by pfent** [TUM-Dev/Campus-Android#914]
Instead of using AlarmManager, we should use [WorkManager](https://developer.android.com/topic/libraries/architecture/workmanager) to schedule tasks.

The current system relies on `BOOT_COMPLETED` and `WIFI_STATE_CHANGED` broadcasts to schedule services, which aren't really reliable on newer versions of Android.
Instead of working around those changes, we should rely on [the robust system Workmanager implements](https://developer.android.com/reference/androidx/work/WorkManager).  This probably also means to change the Services to `OneTimeWorkRequest` or `PeriodicWorkRequest`.

@thellmund maybe this also allows for easier Notification scheduling in #879?

**Comment by thellmund** [comment]
I’m all for using `WorkManager` for actual background work. However, it’s not appropriate for scheduling notifications (see [here](https://stackoverflow.com/a/50311781)).
